@username = user3
@password = password123
@sessionToken = 7mfP0dr1eBBjwbgSCK0oAA635ht6ei2P
@csrfToken = AijqNVDl4HaUuUJYN9vTQea9dwzHQrpe
@bookID = 338uD1dqj1DvZ6b7zezPF6dY3pR
@categoryID = 338uJU9sQ8AV1EZC2wSfapErB6o
@paymentMethodID = 338uMcjcvfit2h1WTrzLRAhxoVl
@expenseID = 338uPWGBEsaS5TMGzEfdsqbFDTU

############################## Health

GET http://localhost:8080/api/health

################################ Auth

POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST http://localhost:8080/api/auth/sign-in
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST http://localhost:8080/api/auth/sign-out
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

###

POST http://localhost:8080/api/auth/sign-out-all
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

###

GET http://localhost:8080/api/auth/csrf-token
Cookie: xpense_session_token={{sessionToken}}

############################ User

GET http://localhost:8080/api/users/exists?username={{username}}

###

GET http://localhost:8080/api/users/me
Cookie: xpense_session_token={{sessionToken}}

###

DELETE http://localhost:8080/api/users/me
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

############################ Book

POST http://localhost:8080/api/books
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "name": "My First Book",
  "description": "This is my first book"
}

###

GET http://localhost:8080/api/books
# GET http://localhost:8080/api/books?page=2&page_size=20
Cookie: xpense_session_token={{sessionToken}}

###

GET http://localhost:8080/api/books/{{bookID}}
Cookie: xpense_session_token={{sessionToken}}

###

PUT http://localhost:8080/api/books/{{bookID}}
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "name": "A New Book Name",
  "description": "Updated description for my book"
}

###

DELETE http://localhost:8080/api/books/{{bookID}}
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

############################ Category

POST http://localhost:8080/api/categories
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "bookID": "{{bookID}}",
  "name": "Food",
  "description": "Expenses for food and groceries"
}

###

GET http://localhost:8080/api/categories?book-id={{bookID}}
Cookie: xpense_session_token={{sessionToken}}

###

GET http://localhost:8080/api/categories/{{categoryID}}
Cookie: xpense_session_token={{sessionToken}}

###

PUT http://localhost:8080/api/categories/{{categoryID}}
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "name": "Food 2",
  "description": "Updated description for food expenses"
}

###

DELETE http://localhost:8080/api/categories/{{categoryID}}
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

############################ Payment Method

POST http://localhost:8080/api/payment-methods
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "bookID": "{{bookID}}",
  "name": "Credit Card",
  "description": "My primary credit card"
}

###

GET http://localhost:8080/api/payment-methods?book-id={{bookID}}
Cookie: xpense_session_token={{sessionToken}}

###

GET http://localhost:8080/api/payment-methods/{{paymentMethodID}}
Cookie: xpense_session_token={{sessionToken}}

###

PUT http://localhost:8080/api/payment-methods/{{paymentMethodID}}
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "name": "A Credit Card",
  "description": "My updated primary credit card"
}

###

DELETE http://localhost:8080/api/payment-methods/{{paymentMethodID}}
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}

############################ Expense

POST http://localhost:8080/api/expenses
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "bookID": "{{bookID}}",
  "categoryID": "{{categoryID}}",
  "paymentMethodID": "{{paymentMethodID}}",
  "date": 1095379200000,
  "amount": 50.75,
  "remark": "Grocery shopping"
}

###

GET http://localhost:8080/api/expenses?book-id={{bookID}}
Cookie: xpense_session_token={{sessionToken}}

###

GET http://localhost:8080/api/expenses/{{expenseID}}
Cookie: xpense_session_token={{sessionToken}}

###
PUT http://localhost:8080/api/expenses/{{expenseID}}
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}
Content-Type: application/json

{
  "bookID": "{{bookID}}",
  "categoryID": "{{categoryID}}",
  "paymentMethodID": "{{paymentMethodID}}",
  "date": 1095379200000,
  "amount": 75.00,
  "remark": "Updated grocery shopping"
}

###

DELETE http://localhost:8080/api/expenses/{{expenseID}}
Cookie: xpense_session_token={{sessionToken}}
X-CSRF-Token: {{csrfToken}}