@username = user1
@password = password123
@session_token = 8daKAUIGK04AJdnNmFQms3wCHyeCDXKV
@csrf_token = 8sWTNWY1nq1oigALnw7XkKLeGb35OWe9
@book_id = 32sfrqn4W7Tteo9dQ22a2mUnXh6
@category_id = 32sfszG1YtMLv4snkJu7I25asZz
@payment_method_id = 32sfw5xJWLeOUU2YHSCBmnsBuOW
@expense_id = 32sgAI3JJmYCkQ48Pefg0i7kmiP

############################## Health

GET http://localhost:8080/api/health

################################ Auth

POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

###

POST http://localhost:8080/api/auth/logout
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}

###

POST http://localhost:8080/api/auth/logout-all
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}

###

GET http://localhost:8080/api/auth/csrf-token
Cookie: session_token={{session_token}}

############################ User

GET http://localhost:8080/api/users/me
Cookie: session_token={{session_token}}

###

DELETE http://localhost:8080/api/users/me
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}

############################ Book

POST http://localhost:8080/api/books
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}
Content-Type: application/json

{
  "name": "My First Book",
  "description": "This is my first book"
}

###

GET http://localhost:8080/api/books
# GET http://localhost:8080/api/books?page=2&page_size=20
Cookie: session_token={{session_token}}

###

GET http://localhost:8080/api/books/{{book_id}}
Cookie: session_token={{session_token}}

###

PUT http://localhost:8080/api/books/{{book_id}}
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}
Content-Type: application/json

{
  "name": "A New Book Name",
  "description": "Updated description for my book"
}

###

DELETE http://localhost:8080/api/books/{{book_id}}
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}

############################ Category

POST http://localhost:8080/api/categories
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}
Content-Type: application/json

{
  "book_id": "{{book_id}}",
  "name": "Food",
  "description": "Expenses for food and groceries"
}

###

GET http://localhost:8080/api/categories?book_id={{book_id}}
Cookie: session_token={{session_token}}

###

GET http://localhost:8080/api/categories/{{category_id}}
Cookie: session_token={{session_token}}

###

PUT http://localhost:8080/api/categories/{{category_id}}
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}
Content-Type: application/json

{
  "name": "Food 2",
  "description": "Updated description for food expenses"
}

###

DELETE http://localhost:8080/api/categories/{{category_id}}
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}

############################ Payment Method

POST http://localhost:8080/api/payment-methods
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}
Content-Type: application/json

{
  "book_id": "{{book_id}}",
  "name": "Credit Card",
  "description": "My primary credit card"
}

###

GET http://localhost:8080/api/payment-methods?book_id={{book_id}}
Cookie: session_token={{session_token}}

###

GET http://localhost:8080/api/payment-methods/{{payment_method_id}}
Cookie: session_token={{session_token}}

###

PUT http://localhost:8080/api/payment-methods/{{payment_method_id}}
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}
Content-Type: application/json

{
  "name": "A Credit Card",
  "description": "My updated primary credit card"
}

###

DELETE http://localhost:8080/api/payment-methods/{{payment_method_id}}
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}

############################ Expense

POST http://localhost:8080/api/expenses
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}
Content-Type: application/json

{
  "book_id": "{{book_id}}",
  "category_id": "{{category_id}}",
  "payment_method_id": "{{payment_method_id}}",
  "date": 1095379200000,
  "amount": 50.75,
  "remark": "Grocery shopping"
}

###

GET http://localhost:8080/api/expenses?book_id={{book_id}}
Cookie: session_token={{session_token}}

###

GET http://localhost:8080/api/expenses/{{expense_id}}
Cookie: session_token={{session_token}}

###
PUT http://localhost:8080/api/expenses/{{expense_id}}
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}
Content-Type: application/json

{
  "book_id": "{{book_id}}",
  "category_id": "{{category_id}}",
  "payment_method_id": "{{payment_method_id}}",
  "date": 1095379200000,
  "amount": 75.00,
  "remark": "Updated grocery shopping"
}

###

DELETE http://localhost:8080/api/expenses/{{expense_id}}
Cookie: session_token={{session_token}}
X-CSRF-Token: {{csrf_token}}