// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: category.sql

package repository

import (
	"context"
)

const createCategory = `-- name: CreateCategory :execrows
INSERT INTO category (
    id,
    book_id,
    name,
    description,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
RETURNING
    id, book_id, name, description, created_at, updated_at
`

type CreateCategoryParams struct {
	ID          string
	BookID      string
	Name        string
	Description string
	CreatedAt   int64
	UpdatedAt   int64
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createCategory,
		arg.ID,
		arg.BookID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
