// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package repository

import (
	"context"
)

const createSession = `-- name: CreateSession :execrows
INSERT INTO session (
    id,
    user_id,
    token,
    csrf_token,
    expires_at,
    created_at,
    updated_at
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
)
RETURNING
    id, user_id, token, csrf_token, expires_at, created_at, updated_at
`

type CreateSessionParams struct {
	ID        string `json:"id"`
	UserID    string `json:"userID"`
	Token     string `json:"token"`
	CsrfToken string `json:"csrfToken"`
	ExpiresAt string `json:"expiresAt"`
	CreatedAt string `json:"createdAt"`
	UpdatedAt string `json:"updatedAt"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.CsrfToken,
		arg.ExpiresAt,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteSessionByExpiresAt = `-- name: DeleteSessionByExpiresAt :execrows
DELETE FROM
    session
WHERE
    expires_at < ?1
`

func (q *Queries) DeleteSessionByExpiresAt(ctx context.Context, expiresAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteSessionByExpiresAt, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByToken = `-- name: GetSessionByToken :many
SELECT
    id, user_id, token, csrf_token, expires_at, created_at, updated_at
FROM
    session
WHERE
    token = ?1
`

func (q *Queries) GetSessionByToken(ctx context.Context, token string) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, getSessionByToken, token)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Token,
			&i.CsrfToken,
			&i.ExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionByToken = `-- name: UpdateSessionByToken :execrows
UPDATE
    session
SET
    expires_at = ?1,
    updated_at = ?2
WHERE
    token = ?3
`

type UpdateSessionByTokenParams struct {
	ExpiresAt string `json:"expiresAt"`
	UpdatedAt string `json:"updatedAt"`
	Token     string `json:"token"`
}

func (q *Queries) UpdateSessionByToken(ctx context.Context, arg UpdateSessionByTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionByToken, arg.ExpiresAt, arg.UpdatedAt, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateSessionByUserID = `-- name: UpdateSessionByUserID :execrows
UPDATE
    session
SET
    expires_at = ?1,
    updated_at = ?2
WHERE
    user_id = ?3
`

type UpdateSessionByUserIDParams struct {
	ExpiresAt string `json:"expiresAt"`
	UpdatedAt string `json:"updatedAt"`
	UserID    string `json:"userID"`
}

func (q *Queries) UpdateSessionByUserID(ctx context.Context, arg UpdateSessionByUserIDParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateSessionByUserID, arg.ExpiresAt, arg.UpdatedAt, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
